### ISSUE TITLE
Suggestion: Change `square.to_int() as usize` to `square.to_index()`

### ISSUE THREAD

**Issue by zanciks** [DoormatIka/alice-chess-engine#9]
Would normally just make a PR for this, but I don't have access to a computer. Wad reading through the code a bit and noticed that in src/bots/basic_bots.rs, in `calculate_piece_sq_with_board()`, square is going to int, and then to usize. Chess::Square has a .to_index() function which could be used for readability.
Just a suggestion though!!

**Comment by zanciks** [comment]
And if you really wanted to, Piece has .to_index() too ;)

**Comment by DoormatIka** [comment]
I didn't know that before... 
The piece and square .to_index() has been done (with some refactors alongside it). Thank you for the suggestion!
